import { type ComponentFactory } from '../component';
import { type TagVirtualNode } from '../view';
import type { Context, ContextProviderValue } from '../context';
import type { DarkElementInstance } from '../shared';
import { type NativeElement, type Hook, EffectTag } from './types';
declare class Fiber<N = NativeElement> {
  id: number;
  nativeElement: N;
  parent: Fiber<N>;
  child: Fiber<N>;
  nextSibling: Fiber<N>;
  alternate: Fiber<N>;
  move: boolean;
  effectTag: EffectTag;
  instance: DarkElementInstance;
  hook: Hook | null;
  provider: Map<Context, ContextProviderValue>;
  effectHost: boolean;
  layoutEffectHost: boolean;
  insertionEffectHost: boolean;
  portalHost: boolean;
  childrenCount: number;
  childrenElementsCount: number;
  marker: string;
  isUsed: boolean;
  idx: number;
  elementIdx: number;
  batched: number | null;
  catchException: (error: Error) => void;
  private static nextId;
  constructor(hook?: Hook, provider?: Fiber['provider'], idx?: number);
  mutate(options: Partial<Fiber<N>>): this;
  markEffectHost(): void;
  markLayoutEffectHost(): void;
  markInsertionEffectHost(): void;
  markPortalHost(): void;
  incrementChildrenElementsCount(count?: number, force?: boolean): void;
  setError(error: Error): void;
}
declare function workLoop(): boolean;
declare function hasChildrenProp(element: DarkElementInstance): element is TagVirtualNode | ComponentFactory;
declare type CreateUpdateCallbackOptions = {
  rootId: number;
  fiber: Fiber;
  forceStart?: boolean;
  onStart: () => void;
};
declare function createUpdateCallback(options: CreateUpdateCallbackOptions): () => void;
export { Fiber, workLoop, hasChildrenProp, createUpdateCallback };
